# Generated by Django 6.0.5 on 2026-07-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('unidad_medida', models.CharField(choices=[('Kg', 'Kilogramos'), ('Mtrs', 'Metros'), ('Unidades', 'Unidades'), ('Ltrs', 'Litros')], max_length=20)),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='insumos/')),
            ],
        ),
        migrations.CreateModel(
            name='LineaEnsamblaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='lineas/')),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='operarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='supervisores/')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Operativa', 'Operativa'), ('En Mantenimiento', 'En Mantenimiento'), ('Detenida', 'Detenida'), ('Falla', 'Falla / Parada No Planificada')], default='Operativa', max_length=50)),
                ('horas_uso', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maquinarias/')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='Produccion.lineaensamblaje')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad_programada', models.PositiveIntegerField()),
                ('cantidad_producida', models.PositiveIntegerField(default=0)),
                ('fecha_inicio_programada', models.DateTimeField()),
                ('fecha_fin_programada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('prioridad_orden', models.PositiveIntegerField(default=1)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.lineaensamblaje')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produccion.maquinaria')),
                ('operario_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produccion.operario')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estimada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_desperdicio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_utilizados', to='Produccion.ordenfabricacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInterrupcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=200)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produccion.maquinaria')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produccion.ordenfabricacion')),
            ],
        ),
    ]
