# Generated by Django 6.0.5 on 2026-07-29 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='contrasena',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
