# Generated by Django 6.0.5 on 2026-07-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0002_remove_supervisor_contrasena_supervisor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleinsumolote',
            old_name='cantidad_desperdicio',
            new_name='cantidad_desperdiciada',
        ),
        migrations.RenameField(
            model_name='detalleinsumolote',
            old_name='cantidad_utilizada',
            new_name='cantidad_usada',
        ),
        migrations.RenameField(
            model_name='registrointerrupcion',
            old_name='fecha_inicio',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='detalleinsumolote',
            name='cantidad_estimada',
        ),
        migrations.RemoveField(
            model_name='registrointerrupcion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='registrointerrupcion',
            name='orden',
        ),
        migrations.AlterField(
            model_name='detalleinsumolote',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumos', to='Produccion.ordenfabricacion'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lineaensamblaje',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lineaensamblaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('Operativa', 'Operativa'), ('En Mantenimiento', 'En Mantenimiento'), ('Detenida', 'Detenida'), ('Falla', 'Falla'), ('Inactiva', 'Inactiva')], default='Operativa', max_length=30),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='horas_uso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias', to='Produccion.lineaensamblaje'),
        ),
        migrations.AlterField(
            model_name='operario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='cantidad_programada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='prioridad_orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registrointerrupcion',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
