# Generated by Django 6.0.5 on 2026-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0003_rename_cantidad_desperdicio_detalleinsumolote_cantidad_desperdiciada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleinsumolote',
            old_name='cantidad_desperdiciada',
            new_name='cantidad_desperdicio',
        ),
        migrations.RenameField(
            model_name='detalleinsumolote',
            old_name='cantidad_usada',
            new_name='cantidad_estimada',
        ),
        migrations.AddField(
            model_name='detalleinsumolote',
            name='cantidad_utilizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
