# Generated by Django 6.0.5 on 2026-07-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0004_rename_cantidad_desperdiciada_detalleinsumolote_cantidad_desperdicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='cantidad_programada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
